name: Test, build, and deploy
on: [push, pull_request]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - if: github.ref != 'refs/heads/develop'
        uses: actions/checkout@v2
        with:
          ref: develop
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - if: github.ref != 'refs/heads/develop'
        run: git branch develop origin/develop

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci --ignore-scripts
      - run: npm run lint
      - run: npm run build
      - run: npm run test:unit

      - run: docker-compose up -d
      - name: Ensure that node is running
        run: |
          while [[ `curl -s -o /dev/null -w %{http_code} localhost:3013/api` != 200 ]]; do
            sleep 0.2;
          done

      - run: npm run test:integration:channel,accounts
      - run: npm run test:integration:contract,chain
      - run: npm run test:integration:else
      - run: npm run report-coverage
        if: always()
      - run: docker-compose logs
        if: always()